# Generated by Django 4.2.1 on 2023-05-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
